name: Test
on:
  pull_request:
  push:
jobs:
  yq-example:
    name: YQ example!
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@v3
    - uses: ./
    - name: "Show folks how to run YQ"
      run: |
        yq --help
